# Generated by Django 3.2.12 on 2022-04-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Blog',
        ),
    ]
